# Generated by Django 3.2.4 on 2021-10-06 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('website', models.URLField(max_length=100)),
                ('located_in', models.TextField(max_length=100)),
                ('address', models.TextField(max_length=254)),
                ('hours', models.TextField(max_length=254)),
                ('appointments_url', models.URLField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('question_answer', models.TextField(max_length=254)),
                ('availability', models.TextField(default='Monday, Tuesday', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50, null=True)),
                ('lname', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=60, null=True)),
                ('inquiry', models.CharField(choices=[(None, 'Nature of Inquiry'), ('Feedback', 'Feedback'), ('Career', 'Career'), ('Support', 'Support')], default='Feedback', max_length=8)),
                ('subject', models.CharField(max_length=50, null=True)),
                ('comment', models.TextField(max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=60)),
                ('response_type', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Health_Practitioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional_title', models.CharField(default='Dr. ', max_length=4)),
                ('professional_suffix', models.CharField(default=' MD', max_length=4)),
                ('telephone', models.CharField(max_length=20)),
                ('specialty', models.TextField(max_length=200)),
                ('consultation_times', models.TextField(default='Monday - 10:00am to 11:00am', max_length=600)),
                ('insurance_accepted', models.CharField(default='Blue Cross', max_length=500)),
                ('languages', models.CharField(default='English', max_length=60)),
                ('accepting_new_patients', models.CharField(default='Yes', max_length=3)),
                ('reviews', models.IntegerField(default=29)),
                ('rating_reviews', models.FloatField(default=4.7)),
                ('patient_comments', models.IntegerField(default=25)),
                ('appointments_pending', models.IntegerField(default=0)),
                ('appointments_approved', models.IntegerField(default=0)),
                ('clinics', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aidApp.clinic')),
                ('health_practitioner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', phone_field.models.PhoneField(blank=True, help_text='Patient phone number', max_length=31)),
                ('D_O_B', models.CharField(max_length=20)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('sex', models.CharField(max_length=20)),
                ('marital_status', models.CharField(max_length=50)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('service_options', models.CharField(max_length=50)),
                ('located_in', models.TextField(max_length=254)),
                ('address', models.TextField(max_length=254)),
                ('hours', models.TextField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('website', models.URLField(max_length=100)),
                ('directions', models.TextField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Contact_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_1', models.TextField(blank=True, null=True)),
                ('address_2', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('zip_code', models.TextField(blank=True, null=True)),
                ('ec_name', models.TextField(blank=True, null=True)),
                ('ec_phone_number', models.TextField(blank=True, null=True)),
                ('ec_address_1', models.TextField(blank=True, null=True)),
                ('ec_address_2', models.TextField(blank=True, null=True)),
                ('ec_city', models.TextField(blank=True, null=True)),
                ('ec_state', models.TextField(blank=True, null=True)),
                ('ec_zip_code', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aidApp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Medical_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_visited', models.DateField(default=django.utils.timezone.now)),
                ('patient_concerns', models.TextField(blank=True, null=True)),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('bP_systolic', models.IntegerField(blank=True, null=True)),
                ('bP_diastolic', models.IntegerField(blank=True, null=True)),
                ('spO2', models.IntegerField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('prescriptions', models.TextField(blank=True, null=True)),
                ('test_results', models.TextField(blank=True, null=True)),
                ('health_practitioner_comments', models.TextField(blank=True, null=True)),
                ('health_practitioner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aidApp.health_practitioner')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aidApp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(default=django.utils.timezone.now)),
                ('timeslots', models.IntegerField(choices=[(0, '9:00 AM'), (1, '10:00 AM'), (2, '11:00 AM'), (3, '12:00 PM'), (4, '1:00 PM'), (5, '2:00 PM'), (6, '3:00 PM'), (7, '4:00 PM'), (8, '5:00 PM')], default=0)),
                ('appt_reason', models.TextField(default='Annual Physical Examination', max_length=200)),
                ('app_status', models.CharField(blank=True, max_length=10)),
                ('health_practitioner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aidApp.health_practitioner')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aidApp.patient')),
            ],
        ),
    ]
