# Generated by Django 3.2.4 on 2021-09-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health_practitioner',
            name='insurance_accepted',
            field=models.CharField(default='Blue Cross', max_length=500),
        ),
        migrations.AlterField(
            model_name='patient',
            name='D_O_B',
            field=models.CharField(max_length=20),
        ),
    ]
