# Generated by Django 3.2.4 on 2021-09-29 19:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aidApp', '0002_auto_20210929_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='D_O_B',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
