# Generated by Django 3.2.4 on 2021-10-01 20:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aidApp', '0005_remove_patient_age'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='appointment',
        #     name='app_date_day',
        # ),
        # migrations.RemoveField(
        #     model_name='appointment',
        #     name='app_date_month',
        # ),
        # migrations.RemoveField(
        #     model_name='appointment',
        #     name='app_date_year',
        # ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Patient_Contact_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_1', models.TextField(blank=True, null=True)),
                ('address_2', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('zip_code', models.TextField(blank=True, null=True)),
                ('ec_name', models.TextField(blank=True, null=True)),
                ('ec_phone_number', models.TextField(blank=True, null=True)),
                ('ec_address_1', models.TextField(blank=True, null=True)),
                ('ec_address_2', models.TextField(blank=True, null=True)),
                ('ec_city', models.TextField(blank=True, null=True)),
                ('ec_state', models.TextField(blank=True, null=True)),
                ('ec_zip_code', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aidApp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Medical_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_visited', models.DateField(default=django.utils.timezone.now)),
                ('patient_concerns', models.TextField(blank=True, null=True)),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('bP_systolic', models.IntegerField(blank=True, null=True)),
                ('bP_diastolic', models.IntegerField(blank=True, null=True)),
                ('spO2', models.IntegerField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('prescriptions', models.TextField(blank=True, null=True)),
                ('test_results', models.TextField(blank=True, null=True)),
                ('health_practitioner_comments', models.TextField(blank=True, null=True)),
                ('health_practitioner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aidApp.health_practitioner')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aidApp.patient')),
            ],
        ),
    ]
