# Generated by Django 3.2.4 on 2021-10-07 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aidApp', '0006_auto_20211001_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_contact_info',
            name='ec_address_1',
        ),
        migrations.RemoveField(
            model_name='patient_contact_info',
            name='ec_address_2',
        ),
        migrations.RemoveField(
            model_name='patient_contact_info',
            name='ec_city',
        ),
        migrations.RemoveField(
            model_name='patient_contact_info',
            name='ec_name',
        ),
        migrations.RemoveField(
            model_name='patient_contact_info',
            name='ec_phone_number',
        ),
        migrations.RemoveField(
            model_name='patient_contact_info',
            name='ec_state',
        ),
        migrations.RemoveField(
            model_name='patient_contact_info',
            name='ec_zip_code',
        ),
        migrations.AddField(
            model_name='patient',
            name='race_or_ethnicity',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='health_practitioner',
            name='health_practitioner',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient_contact_info',
            name='address_1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patient_contact_info',
            name='address_2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patient_contact_info',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patient_contact_info',
            name='patient',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='aidApp.patient'),
        ),
        migrations.AlterField(
            model_name='patient_contact_info',
            name='state',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patient_contact_info',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Emergency_Contact_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ec_name', models.CharField(blank=True, max_length=30, null=True)),
                ('ec_phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('ec_email', models.CharField(blank=True, max_length=30, null=True)),
                ('ec_address_1', models.CharField(blank=True, max_length=30, null=True)),
                ('ec_address_2', models.CharField(blank=True, max_length=30, null=True)),
                ('ec_city', models.CharField(blank=True, max_length=30, null=True)),
                ('ec_state', models.CharField(blank=True, max_length=30, null=True)),
                ('ec_zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('patient', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='aidApp.patient')),
            ],
        ),
    ]
