# Generated by Django 3.2.4 on 2021-10-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidApp', '0008_auto_20211012_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='app_status',
            field=models.IntegerField(default=0),
        ),
    ]
