# Generated by Django 3.2.4 on 2021-10-18 22:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('aidApp', '0010_alter_appointment_health_practitioner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='D_O_B',
            field=models.CharField(default=datetime.datetime(2021, 10, 18, 22, 48, 28, 343242, tzinfo=utc), max_length=20),
        ),
    ]
