# Generated by Django 3.2.4 on 2021-10-21 21:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aidApp', '0012_alter_patient_d_o_b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency_contact_info',
            name='patient',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='aidApp.patient'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medical_history',
            name='health_practitioner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aidApp.health_practitioner'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medical_history',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aidApp.patient'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='D_O_B',
            field=models.CharField(default=datetime.date(2021, 10, 21), max_length=20),
        ),
        migrations.AlterField(
            model_name='patient_contact_info',
            name='patient',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='aidApp.patient'),
            preserve_default=False,
        ),
    ]
